CREATE TABLE bank_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_name TEXT NOT NULL,
  balance_cents BIGINT NOT NULL CHECK (balance_cents >= 0),
  iban TEXT NOT NULL,
  bic TEXT NOT NULL,
  UNIQUE (bic, iban)
);

CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  counterparty_name TEXT NOT NULL,
  counterparty_iban TEXT NOT NULL,
  counterparty_bic TEXT NOT NULL,
  amount_cents BIGINT NOT NULL CHECK (amount_cents < 0),
  amount_currency TEXT NOT NULL CHECK (amount_currency = 'EUR'),
  bank_account_id BIGINT NOT NULL REFERENCES bank_accounts(id),
  description TEXT NOT NULL
);

CREATE INDEX transactions_bank_account_id_idx ON transactions (bank_account_id);

CREATE TABLE idempotency_requests (
  idempotency_key TEXT PRIMARY KEY,
  request_fingerprint TEXT NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE
);
